name: ci
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build Docker image and Push to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: chohoward/django-locallibrary
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Docker build image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Run tests
        id: tests
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }} python3 manage.py test
      - name: Docker build and push image
        if: ${{ steps.tests.outcome == 'success' }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
